language: rust

rust:
  - stable

branches:
  only:
    - staging
    - trying
    - master

cache: cargo

addons:
  apt:
    packages:
      - python3-pip
      - python3-dev

env:
  global:
    - SVD2RUST=0.16.1
  matrix:
    - CRATES=stm32f0
    - CRATES=stm32f1
    - CRATES=stm32f2
    - CRATES=stm32f3
    - CRATES=stm32f4
    - CRATES=stm32f7
    - CRATES=stm32h7
    - CRATES=stm32l0
    - CRATES=stm32l1
    - CRATES=stm32l4
    - CRATES=stm32g0
    - CRATES=stm32g4

install:
  - pip3 install --user setuptools wheel
  - pip3 install --user pyyaml
  - scripts/svd2rust_install.sh $SVD2RUST
  - rustup component add rustfmt

# disabling incremental build gives a nice speedup for check...
script:
  - make all
  - CARGO_INCREMENTAL=0 make check
