language: rust

rust:
  - stable

cache: cargo

addons:
  apt:
    packages:
      - python3-yaml

env:
  - SVD2RUST=0.14.0
  - CRATES=stm32f0
  - CRATES=stm32f1
  - CRATES=stm32f2
  - CRATES=stm32f3
  - CRATES=stm32f4
  - CRATES=stm32f7
  - CRATES=stm32h7
  - CRATES=stm32l0
  - CRATES=stm32l1
  - CRATES=stm32l4

install:
  - scripts/svd2rust_install.sh $SVD2RUST
  - rustup component add rustfmt

# disabling incremental build gives a nice speedup for check...
script:
  - make all
  - CARGO_INCREMENTAL=0 make check
