make_mod = true
generic_mod = true
strict = true
max_cluster_size = true
atomics = true
atomics_feature = "atomics"
debug_impl = true
defmt_impl = "defmt"
reexport_core_peripherals = true
reexport_interrupt = true

[ident_formats.register_spec]
case = "constant"
suffix = "rs"

[ident_formats.enum_name]
case = "constant"

[ident_formats.enum_write_name]
case = "constant"

[ident_formats.enum_value]
case = "pascal"

[ident_formats.field_reader]
case = "constant"
suffix = "r"

[ident_formats.field_writer]
case = "constant"
suffix = "w"
