name: compare mmaps

on:
  pull_request_target:
    paths:
      - 'svd/**'
      - 'devices/**'
      - 'cortex_m/**'
      - 'peripherals/**'
      - 'Makefile'
      - 'Makefile.toml'
      - 'scripts/tool_install.sh'

jobs:
  compare:
    name: Compare mmaps
    runs-on: ubuntu-latest
    continue-on-error: true

    env:
      SVDTOOLS: svdtools

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          path: master

      - name: Checkout pull request
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.number }}/head
          path: pr

      - name: Checkout mmaps
        uses: actions/checkout@v3
        with:
          repository: stm32-rs/stm32-rs-mmaps
          ssh-key: ${{ secrets.MMAPS_KEY }}
          path: mmaps

      - name: Add fictive crate
        run: |
          cargo init

      - name: Install tools
        run: |
          ./master/scripts/tool_install.sh svdtools

      - name: Build and publish
        run: |
          # Grab commit ID from checked out PR
          cd pr
          COMMIT=$(git rev-parse --short HEAD)
          BRANCH=pr-${{ github.event.number }}-$COMMIT
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

          # Use the PR's YAML files to rebuild mmaps
          cd ../master
          rm -rf devices peripherals
          mv ../pr/devices ../pr/peripherals .
          make -j2 mmaps

          # Use the new mmaps to make a commit in the mmaps repo
          mv mmaps/* ../mmaps/
          cd ../mmaps
          git checkout -b $BRANCH
          git add .
          git config user.name "stm32-rs builder"
          git config user.email "action@github.com"
          git commit --allow-empty -m "stm32-rs PR #${{ github.event.number }} $COMMIT"
          git push -f origin $BRANCH
      - name: Comment
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            [Memory map comparison](https://github.com/stm32-rs/stm32-rs-mmaps/compare/${{ env.BRANCH }})
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
