name: build mmaps

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build mmaps
    runs-on: ubuntu-20.04

    env:
      SVDTOOLS: svdtools

    steps:
      - name: Checkout stm32-rs
        uses: actions/checkout@v3
        with:
          path: stm32-rs

      - name: Checkout mmaps
        uses: actions/checkout@v3
        with:
          repository: stm32-rs/stm32-rs-mmaps
          ssh-key: ${{ secrets.MMAPS_KEY }}
          path: stm32-rs-mmaps

      - name: Add fictive crate
        run: |
          cargo init

      - name: Install tools
        run: |
          ./scripts/tool_install.sh svdtools

      - name: Build and publish
        run: |
          cd stm32-rs
          COMMIT=$(git rev-parse HEAD)
          make -j2 mmaps
          mv mmaps/* ../stm32-rs-mmaps/
          cd ../stm32-rs-mmaps
          git config user.name "stm32-rs builder"
          git config user.email "action@github.com"
          git add .
          git commit --allow-empty -m "stm32-rs master $COMMIT"
          git push origin master
