name: build nightlies

env:
  SVDTOOLS_VERSION: v0.2.5
  SVD2RUST_VERSION: v0.25.0
  FORM_VERSION: v0.10.0

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    env:
      SVDTOOLS: svdtools

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          path: stm32-rs

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true

      - name: Add fictive crate
        run: |
          cargo init

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install tools
        run: make install

      - name: Deploy SSH key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.NIGHTLIES_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com
      - name: Build and publish
        run: |
          mkdir nightly
          cd stm32-rs
          COMMIT=$(git rev-parse HEAD)
          make -j2 form
          mv stm32{f,g,h,l,mp,wl,wb}* ../nightly
          cp .github/workflows/README-nightlies.md ../nightly/README.md
          cd ../nightly
          git init
          git add .
          git config user.name "stm32-rs builder"
          git config user.email "action@github.com"
          git commit -m "stm32-rs master $COMMIT"
          git remote add origin git@github.com:stm32-rs/stm32-rs-nightlies
          git push --force origin master
